version: '3.9'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: finances-backend
    depends_on:
      - db
    env_file:
      - ./prod.env
    ports:
      - 3080:3080
    restart: on-failure
    volumes:
      - ./:/var/app # Named volume for all files.
      - /var/app/node_modules # Anonymous volume for node_modules only to fix issue with bcrypt.

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile.dev
    container_name: finances-db
    env_file:
      - ./prod.env
    ports:
      - 5432:5432
    restart: on-failure
