version: '3.9'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: personal-app-server
    depends_on:
      - database
    env_file:
      - ./dev.env
    ports:
      - 3080:3080
    restart: on-failure
    volumes:
      - ./:/var/app # Named volume for all files.
      - /var/app/node_modules # Anonymous volume for node_modules only to fix issue with bcrypt.

  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile.dev
    container_name: personal-app-database
    env_file:
      - ./dev.env
    ports:
      - 5432:5432
    restart: on-failure
