version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.backend.dev
    container_name: budgetello-api
    depends_on:
      - database
    env_file:
      - ./dev.env
    ports:
      - 3080:3080
    restart: on-failure
    volumes:
      - ./:/var/app
      - /var/run/docker.sock:/var/run/docker.sock # Add this line to mount the Docker socket

  database:
    build:
      context: ./
      dockerfile: ./database/Dockerfile.database.dev
    container_name: budgetello-database
    env_file:
      - ./dev.env
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - .:/var/app
