FROM ubuntu:22.04

WORKDIR /var/app

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs

EXPOSE 3080

CMD npm run dev
