FROM ubuntu:22.04

WORKDIR /var/app

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs

# Install Docker client
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh
RUN usermod -aG docker root

EXPOSE 3080

CMD echo "bash /var/app/database/scripts/init-db.sh" | docker exec -i budgetello-database bash && npm run dev
