### Finance category type #####################################################
GET http://localhost:3080/api/finances/category-types
Authorization: MY_TOKEN

###
GET http://localhost:3080/api/finances/category-types?ids=1
Authorization: MY_TOKEN

###
GET http://localhost:3080/api/finances/category-types/2
Authorization: MY_TOKEN



### Finance category ##########################################################
GET http://localhost:3080/api/finances/categories
Authorization: MY_TOKEN

###
GET http://localhost:3080/api/finances/categories/10
Authorization: MY_TOKEN

###
POST http://localhost:3080/api/finances/categories
Authorization: MY_TOKEN
Content-Type: application/json

{
	"name": "My category name",
	"typeId": 2
}

###
PATCH http://localhost:3080/api/finances/categories/16
Authorization: MY_TOKEN
Content-Type: application/json

{
	"name": "My UPDATED category name",
	"typeId": 1
}

###
DELETE http://localhost:3080/api/finances/categories/4
Authorization: MY_TOKEN



### Finance record ############################################################
GET http://localhost:3080/api/finance-record?take=4&skip=200
Authorization: MY_TOKEN

###
GET http://localhost:3080/api/finance-record/250
Authorization: MY_TOKEN

###
POST http://localhost:3080/api/finance-record
Authorization: MY_TOKEN
Content-Type: application/json

{
	"amount": 5432,
	"categoryId": 3,
	"date": "2021-10-02"
}

###
PATCH http://localhost:3080/api/finance-record/330
Authorization: MY_TOKEN
Content-Type: application/json

{
	"amount": 2345,
	"categoryId": 4,
	"date": "2021-10-01",
	"isTrashed": true
}

###
DELETE http://localhost:3080/api/finance-record/331
Authorization: MY_TOKEN



### User ######################################################################
GET http://localhost:3080/api/users
Authorization: MY_TOKEN

###
GET http://localhost:3080/api/users/0
Authorization: MY_TOKEN

###
GET http://localhost:3080/api/users/search?id=3&username=sasha
Authorization: MY_TOKEN

###
POST http://localhost:3080/api/users
Content-Type: application/json

{
	"username": "johndoe",
	"password": "pass123"
}

###
PATCH http://localhost:3080/api/users/3
Authorization: MY_TOKEN
Content-Type: application/json

{
	"username": "johndoe",
	"password": "pass123"
}

###
DELETE http://localhost:3080/api/users/3
Authorization: MY_TOKEN



### Auth ######################################################################
POST http://localhost:3080/api/login
Content-Type: application/json

{
	"username": "username",
	"password": "password"
}
