FROM postgres:15.3

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl jq lzop
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs

EXPOSE 5432
